{{- if and .Values.controller.enabled .Values.controller.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "AGH3.fullname" . }}-controller-clusterrolebinding
  labels:
    {{- include "AGH3.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "AGH3.fullname" . }}-controller-clusterrole
subjects:
- kind: ServiceAccount
  name: {{ include "controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
