{{- if and .Values.controller.enabled (and .Values.controller.secret.enabled .Values.controller.secret.minio.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.controller.secret.minio.secretName }}
  labels:
    {{- include "AGH3.labels" . | nindent 4 }}
stringData:
  executor-minio-user: {{ (required "controller.secret.minio.user is required" .Values.controller.secret.minio.user) | quote }}
  executor-minio-password: {{
    (
      default
        .Values.controller.secret.minio.password
        (
          include "specify-password"
            (
              dict
                "domain" "app.argushack.com"
                "token" .Values.keygen.apiToken
                "prefix" .Values.controller.secret.minio.secretName
            )
        )
    ) | substr 0 40 | quote
  }}
{{- end }}
