{{- if .Values.controller.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: controller-role-binding
  labels:
    {{- include "AGH3.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: controller-role
subjects:
  - kind: ServiceAccount
    name: controller-sa
    namespace: {{ .Release.Namespace }}
{{- end }}
