{{- if and .Values.controller.enabled .Values.controller.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "controller.serviceAccountName" . }}
  labels:
    {{- include "AGH3.labels" . | nindent 4 }}
{{- end }}
