{{- if and .Values.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    {{- include "AGH3.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      {{- include "ui.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: ui
          image: {{ include "ui.image" . }}
          ports:
            - name: web
              containerPort: 80
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
      restartPolicy: Always
{{- end }}
