{{- if and .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    {{- include "AGH3.labels" . | nindent 4 }}
spec:
  selector:
    app: ui
  ports:
    - port: 80
      targetPort: web
{{- end }}
