{{- if and .Values.captain.enabled .Values.captain.secret.enabled .Values.captain.secret.superadmin.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.captain.secret.superadmin.secretName }}
  labels:
    {{- include "AGH3.labels" . | nindent 4 }}
stringData:
  SUPERADMIN_PASSWORD: {{
    (
      default
        .Values.captain.secret.superadmin.password
        (
          include "specify-password"
            (
              dict
                "domain" "app.argushack.com"
                "token" .Values.keygen.apiToken
                "prefix" .Values.captain.secret.superadmin.secretName
            )
        )
    ) | quote
  }}
{{- end }}
