{{- if and .Values.captain.enabled .Values.captain.secret.enabled .Values.captain.secret.oidc.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.captain.secret.oidc.secretName }}
  labels:
    {{- include "AGH3.labels" . | nindent 4 }}
stringData:
  url: {{ .Values.captain.secret.oidc.url | quote }}
  client-id: {{ .Values.captain.secret.oidc.clientID | quote }}
  client-secret: {{ .Values.captain.secret.oidc.clientSecret | quote }}
  realm: {{ .Values.captain.secret.oidc.realm | quote }}
{{- end }}
