{{- if and .Values.captain.enabled .Values.captain.secret.enabled .Values.captain.secret.db.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.captain.secret.db.secretName }}
  labels:
    {{- include "AGH3.labels" . | nindent 4 }}
stringData:
  DB_CONN_STR: {{ include "db-connection-string"
    (
      dict
        "db" (
          merge
            .Values.captain.secret.db
            .Values.db.connection
            (
              dict
                "password" (
                  include "specify-password"
                    (
                      dict
                        "domain" "app.argushack.com"
                        "token" .Values.keygen.apiToken
                        "prefix" .Values.captain.secret.db.secretName
                    )
                )
            )
        )
        "context" $
    ) | quote }}
{{- end }}
