{{- if .Values.captain.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: captain
  labels:
    {{- include "AGH3.labels" . | nindent 4 }}
spec:
  selector:
    app: captain
  ports:
    - port: 8080
      targetPort: http
{{- end }}
