{{- if .Values.captain.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: captain-clusterrolebinding
  labels:
    {{- include "AGH3.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: captain-clusterrole
subjects:
- kind: ServiceAccount
  name: captain-sa
  namespace: {{ .Release.Namespace }}
{{- end }}
