{{- if and .Values.captain.enabled .Values.captain.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "captain.serviceAccountName" . }}
  labels:
    {{- include "AGH3.labels" . | nindent 4 }}
{{- end }}
