apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.crds.cm.name }}
  labels:
    {{- include "AGH3.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
data:
  actions.crds.yaml: |-
    {{ .Files.Get "crds/actions.crds.yaml" | nindent 4 }}
