apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "actions-crds-job.serviceAccountName" . }}
  labels:
    {{- include "AGH3.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
