{{- if and .Values.template.enabled (and .Values.template.secret.enabled .Values.template.secret.db.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.template.secret.db.secretName }}
  labels:
    {{- include "AGH2.labels" . | nindent 4 }}
data:
  DB_CONN_STR: {{ include "connection-string" (dict "db" (merge .Values.template.secret.db .Values.db.connection .)) }}
{{- end }}
