{{- if .Values.template.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: template
  labels:
    {{- include "AGH2.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: template
  template:
    metadata:
      labels:
        app: template
    spec:
      {{- include "template.imagePullSecrets" . | nindent 6 }}
      initContainers:
        - name: template-init-postgresql
          image: {{ include "db.image" . }}
          env:
            - name: PG_CONN_STR
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.exploitmgr.secret.db.secretName }}
                  key: DB_CONN_STR
          command:
            [
              "sh",
              "-c",
              "until pg_isready -d $PG_CONN_STR; do echo waiting for postgresql; sleep 1; done",
            ]
      containers:
        - name: template
          image: {{ include "template.image" . }}
          command:
            - ./template
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if .Values.core.enabled }}
            - name: CORE_URL
              value: "core.$(NAMESPACE).svc.cluster.local:50005"
            {{- end }}
            {{- if .Values.exploitmgr.enabled }}
            - name: EXPLOITMGR_URL
              value: "exploitmgr.$(NAMESPACE).svc.cluster.local:50005"
            {{- end }}
            - name: DB_Conn
              valueFrom:
                secretKeyRef:
                  key: DB_CONN_STR
                  name: {{ .Values.exploitmgr.secret.db.secretName }}
            {{- if .Values.transformer.extraEnv }}
            {{- include "common.tplvalues.render" (dict "value" .Values.transformer.extraEnv "context" $) | nindent 12 }}
            {{- end }}
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - name: grpc
              containerPort: 50005
          imagePullPolicy: {{ .Values.template.image.pullPolicy }}
      restartPolicy: Always
{{- end }}