## Default values for AGH3-Playground.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass
##

## @param global.imageRegistry Global Docker Image registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
## @param global.storageClass Global storage class for dynamic provisioning
## @param global.volumePermissions.enabled Enable init container that changes the owner and group of the persistent volume(s) mountpoint to `runAsUser:fsGroup`
##
global:
  imageRegistry: "registry.lkc-lab.com"
  imagePullSecrets:
    - lkc-registry
  storageClass: ""
  volumePermissions:
    enabled: true
## @section Common parameters
##

## @param customRegistrySecret.enabled Enable custom registry secret generation
##
customRegistrySecret:
  ## @skip customRegistrySecret.secretName
  ## Name of the generated secret
  ## !!! DO NOT CHANGE IF YOU DON'T KNOW WHAT YOU ARE DOING !!!
  ##
  secretName: lkc-registry
  enabled: true
  ## @param customRegistrySecret.auth.registry URL of the registry server
  ## @param customRegistrySecret.auth.username Username to authenticate with the registry server
  ## @param customRegistrySecret.auth.password Password to authenticate with the registry server
  auth:
    registry: registry.lkc-lab.com
    username: ""
    password: ""
## @param ingress.enabled Enable ingress controller
## @param ingress.host Ingress hostname
##
ingress:
  enabled: true
  host: ""
  ## @section TLS parameters
  ##
  tls:
    ## @param ingress.tls.enabled Enable TLS certificate generation
    ## @param ingress.tls.secretName Name of the generated secret
    ## @param ingress.tls.cert Server certificate content
    ## @param ingress.tls.key Server private key content
    ##
    enabled: false
    secretName: agh-playground-tls
    cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZFRENDQXZpZ0F3SUJBZ0lVV1BvMjlXUGtjOTYwWGNQMWhkMzFFKzBFUkZnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1p6RUxNQWtHQTFVRUJoTUNWRmN4RHpBTkJnTlZCQWdNQmxSaGFYZGhiakVQTUEwR0ExVUVCd3dHVkdGcApjR1ZwTVNBd0hnWURWUVFLREJkTVpYVnJiMk41ZEdVdFRHRmlJRU52TGl3Z1RIUmtMakVVTUJJR0ExVUVBd3dMCmJHdGpMV3hoWWk1amIyMHdJQmNOTWpJeE1USXpNRGd5TkRJMldoZ1BNakV5TWpFd016QXdPREkwTWpaYU1JR0MKTVFzd0NRWURWUVFHRXdKVVZ6RVBNQTBHQTFVRUNBd0dWR0ZwZDJGdU1SZ3dGZ1lEVlFRSERBOU9aWGNnVkdGcApjR1ZwSUVOcGRIa3hJREFlQmdOVkJBb01GMHhsZFd0dlkzbDBaUzFNWVdJZ1EyOHVMQ0JNZEdRdU1Rd3dDZ1lEClZRUUxEQU5TUkZReEdEQVdCZ05WQkFNTUQzSmtkQzVzYTJNdGJHRmlMbU52YlRCWk1CTUdCeXFHU000OUFnRUcKQ0NxR1NNNDlBd0VIQTBJQUJHd0NKOWswZDN5U1VOSnpXUzlXS0x3Mm9OVkpuMW9MVkEralpzTlo1WGMvU2xsNgpWaGZDYlkvYTFLdTBlYjQxM1hIL3ZLUjBWU2pDQndlZ1RyVTBXOHlqZ2dGZk1JSUJXekNDQVJjR0ExVWRFUVNDCkFRNHdnZ0VLZ2c5eVpIUXViR3RqTFd4aFlpNWpiMjJDRVNvdWNtUjBMbXhyWXkxc1lXSXVZMjl0Z2hSc1l6QXgKTG5Ka2RDNXNhMk10YkdGaUxtTnZiWUlXS2k1c1l6QXhMbkprZEM1c2EyTXRiR0ZpTG1OdmJZSVViR013TWk1eQpaSFF1Ykd0akxXeGhZaTVqYjIyQ0Zpb3ViR013TWk1eVpIUXViR3RqTFd4aFlpNWpiMjJDRkd4ak1ETXVjbVIwCkxteHJZeTFzWVdJdVkyOXRnaFlxTG14ak1ETXVjbVIwTG14cll5MXNZV0l1WTI5dGdoUnNZekEwTG5Ka2RDNXMKYTJNdGJHRmlMbU52YllJV0tpNXNZekEwTG5Ka2RDNXNhMk10YkdGaUxtTnZiWUlVYkdNd05TNXlaSFF1Ykd0agpMV3hoWWk1amIyMkNGaW91YkdNd05TNXlaSFF1Ykd0akxXeGhZaTVqYjIwd0hRWURWUjBPQkJZRUZIeGF1a3dDCllibkF6S1lsZk9Lc2FnaWNNTjl5TUI4R0ExVWRJd1FZTUJhQUZBOWh6ZUJQdWVuRGZ2aTZTUXpzT0l3VHIrRlcKTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElDQVFEQTBnM3VWcVpTanhURFpXNFJmTzZjRnNROW1pTTdrQUFsRW50RApTV2FJQW1TVVI3UUZPazFQVjdMNFJFL0lubTA2Qm9yb0RUSVY3TTBMbnFmVjdVaENIbVVmUXdFbEhwSnYxMGV2CnFZZUluMThkSlJxWng0dFh4c3o1eHBLOGMrMHZieG1hWEFna3ZHRmtHVXNSNG1YUzRiK3V2ckN0ZVUrUGFnbGIKT2pjd2V4Qk1NZ0ZtNDU1VUtVald1VjdoN3VaNGpyRVdVbU53ZVcyR0xBMjFoaXg3VkZxTG9aSlFTby93NjkzZAptVUtGaW5Sb0Myd0lLOStVMExJVXNnU21wbWFLdmROUFFKajB1MlhpOWZzbmdwQnV5SWozSjNpNURVczV1aW04CkZmbUtqN3lKY1NaWkV0MmxYY3lCLzJDUEo1ZW8rbEFLK3YxZVpmcGQzSytYeitaQVpGRDVxbGJ0SHl3Vk5tMkQKdHhHL1N1d05UNnpDbTVLNUI3ZWhTWFMyZ2Q3cGNSSFFmZUk5OGtwUHJsT3R5RXB4YU1jL1hWT0o4QytoSnBsQQpjOVg3bml1WmJNME9WdHlxdERLVGtpTzFFRVYxNUFPUGZvaWh6QlJtTGsxaGxrbnZwQWlxU1QzSFlsT0JpWGhrCnp3MTl3SUlTNTA3N3I5SkFrRmlRQ3FMMVdiM0FlbjVaSkxQa2FUYnNyMExGUmFlZTMwQUswZmIwYUpscnE3N0YKUHlacnhUMXp2MC9nZGNneG50dmtMbXpId2hGV1FtQWVJaWphVm05dXJTQ1p6dXVWL2pQRkdIZHY3K3pGS1ZueQp0eFhlUG1jT0plT2NUcG9PRVNwbW5rNW1XZTlVK3UwbncvMzlEbW4rcm04K3ZiYW0vUUVFSWdXUnBKd2V0N3lBClgvR0Y2UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    key:
## @section AGH3-CTR-Playground parameters
## @descriptionStart
## Playground module for AGH3.
## ref: https://github.com/Leukocyte-Lab/AGH3-CTR-Playground
## @descriptionEnd
##
playground:
  ## @param playground.enabled Enable Playground module
  ##
  enabled: true
  ## @param playground.image.repository Playground image repository
  ## @param playground.image.tag Playground image tag (immutable tags are recommended)
  ## @param playground.image.pullPolicy Playground image pull policy
  ## @param playground.image.pullSecrets Specify docker-registry secret names as an array
  ##
  image:
    repository: leukocyte-lab/argushack3/ctr-playground
    tag: v1.2.0
    pullPolicy: IfNotPresent
    pullSecrets: []
  ## @param playground.secret.enabled Enable secret generate for Playground
  ##
  secret:
    enabled: true # Manually create secrets named as the value of `playground.secret.name` if set to false
    ## @param playground.secret.firebase.enabled Enable secret generate for Playground Firebase
    ## @param playground.secret.firebase.apiKey Firebase API key
    ## @param playground.secret.firebase.authDomain Firebase auth domain
    ## @param playground.secret.firebase.projectId Firebase project ID
    ## @param playground.secret.firebase.storageBucket Firebase storage bucket
    ## @param playground.secret.firebase.messagingSenderId Firebase messaging sender ID
    ## @param playground.secret.firebase.appId Firebase app ID
    ## @param playground.secret.firebase.measurementId Firebase measurement ID
    ##
    firebase:
      ## @skip playground.secret.firebase.secretName
      ## Secret name for Playground Firebase
      ## !!! DO NOT CHANGE IF YOU DON'T KNOW WHAT YOU ARE DOING !!!
      ##
      secretName: playground-firebase-secrets
      enabled: true
      apiKey: ""
      authDomain: ""
      projectId: ""
      storageBucket: ""
      messagingSenderId: ""
      appId: ""
      measurementId: ""
  ## @section Playground service provisioning parameters
  ##
  ## @param playground.service.backendRef.kind Backend Service kind (available options: Service, ExternalService)
  ## @param playground.service.backendRef.namespace Backend Service namespace, leave empty for the same namespace as the chart
  ## @param playground.service.backendRef.name Backend Service name
  ## @param playground.service.backendRef.port Backend Service port
  ## @param playground.service.backendRef.protocol Backend Service protocol
  ## @param playground.service.backendRef.endpoint Backend Service endpoint for the Playground service (required and must be full URL when playground.service.backendRef.kind is ExternalService, only the path or leave empty when playground.service.backendRef.kind is Service)
  ##
  service:
    backendRef:
      kind: "Service"
      namespace: ""
      name: "captain"
      port: 8080
      protocol: "HTTP"
      endpoint: ""
  ## @param playground.extraEnv UI additional environment variables
  ##
  extraEnv: {}
