apiVersion: v1
kind: ConfigMap
metadata:
  name: opendkim-config
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
data:
  opendkim.conf.erb: |
    # This is a basic configuration for signing and verifying. It can easily be
    # adapted to suit a basic installation. See opendkim.conf(5) and
    # /usr/share/doc/opendkim/examples/opendkim.conf.sample for complete
    # documentation of available configuration parameters.

    Syslog			yes
    SyslogSuccess		yes
    #LogWhy			no

    # Common signing and verification parameters. In Debian, the "From" header is
    # oversigned, because it is often the identity key used by reputation systems
    # and thus somewhat security sensitive.
    Canonicalization	relaxed/simple
    Mode			sv
    #SubDomains		no
    OversignHeaders		From

    # Signing domain, selector, and key (required). For example, perform signing
    # for domain "example.com" with selector "2020" (2020._domainkey.example.com),
    # using the private key stored in /etc/dkimkeys/example.private. More granular
    # setup options can be found in /usr/share/doc/opendkim/README.opendkim.
    Domain			<%= domain %>
    Selector		default
    KeyFile		    /etc/domainkey/key.private

    # In Debian, opendkim runs as user "opendkim". A umask of 007 is required when
    # using a local socket with MTAs that access the socket as a non-privileged
    # user (for example, Postfix). You may need to add user "postfix" to group
    # "opendkim" in that case.
    UserID			opendkim
    UMask			007

    # Socket for the MTA connection (required). If the MTA is inside a chroot jail,
    # it must be ensured that the socket is accessible. In Debian, Postfix runs in
    # a chroot in /var/spool/postfix, therefore a Unix socket would have to be
    # configured as shown on the last line below.
    #Socket			local:/run/opendkim/opendkim.sock
    # Socket			inet:8891@10.5.0.6
    Socket			inet:8891
    #Socket			local:/var/spool/postfix/opendkim/opendkim.sock

    #PidFile			/run/opendkim/opendkim.pid

    # Hosts for which to sign rather than verify, default is 127.0.0.1. See the
    # OPERATION section of opendkim(8) for more information.
    #InternalHosts		192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12

    # The trust anchor enables DNSSEC. In Debian, the trust anchor file is provided
    # by the package dns-root-data.
    #TrustAnchorFile		/usr/share/dns/root.key
    #Nameservers		127.0.0.1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postfix-config
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
data:
  main.cf: |
    # See /usr/share/postfix/main.cf.dist for a commented, more complete version

    # Debian specific:  Specifying a file name will cause the first
    # line of that file to be used as the name.  The Debian default
    # is /etc/mailname.
    #myorigin = /etc/mailname

    smtpd_banner = $myhostname ESMTP $mail_name (Debian/GNU)
    biff = no

    # appending .domain is the MUA's job.
    append_dot_mydomain = no

    # Uncomment the next line to generate "delayed mail" warnings
    #delay_warning_time = 4h

    readme_directory = no

    # See http://www.postfix.org/COMPATIBILITY_README.html -- default to 3.6 on
    # fresh installs.
    compatibility_level = 3.6

    # TLS parameters
    smtpd_tls_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
    smtpd_tls_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    smtpd_tls_security_level=may

    smtp_tls_CApath=/etc/ssl/certs
    smtp_tls_security_level=may
    smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache


    smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination
    myhostname = smtp.bas-mail-test.com
    mydomain = bas-mail-test.com
    lmtp_host_lookup = native
    smtp_host_lookup = native
    alias_maps = hash:/etc/aliases
    alias_database = hash:/etc/aliases
    #mydestination = $myhostname, /etc/mailname, localhost, localhost.localdomain, localhost
    relayhost =
    mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 0.0.0.0/0
    mailbox_size_limit = 0
    recipient_delimiter = +
    inet_interfaces = all
    #inet_protocols = all
    inet_protocols = ipv4

    maillog_file = /dev/stdout

    # Milter configuration
    milter_default_action = accept
    milter_protocol = 6
    smtpd_milters = inet:127.0.0.1:8891
    non_smtpd_milters = inet:127.0.0.1:8891
