apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postfix.fullname" . }}
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "postfix.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "postfix.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "imagePullSecrets" . | nindent 6 }}
      containers:
        - name: postfix
          image: {{ include "image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: smtp
              containerPort: 25
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: mydomain
              value: {{ .Values.mydomain }}
            - name: mail_myhostname
              value: {{ .Values.mail_myhostname }}
        - name: dkim
          image: {{ include "dkim.image" . }}
          imagePullPolicy: {{ .Values.dkim.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              mkdir -p /etc/domainkey
              cp /tmp/key.private /etc/domainkey
              chown opendkim:opendkim /etc/domainkey/key.private
              chmod 600 /etc/domainkey/key.private

              erb domain="$domain" /opendkim.conf.erb > /etc/opendkim.conf
              opendkim -f 
          volumeMounts:
            - name: opendkim-config
              mountPath: /opendkim.conf.erb
              subPath: opendkim.conf.erb
            - name: domainkey
              readOnly: false
              mountPath: /tmp/key.private
              subPath: key.private
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: domain
              value: {{ .Values.domain }}
      volumes:
        - name: opendkim-config
          configMap:
            name: opendkim-config
            items:
              - key: opendkim.conf.erb
                path: opendkim.conf.erb
        - name: domainkey
          secret:
            secretName: rsa-private-key
