apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-aio
spec:
  selector:
    app: {{ .Release.Name }}-aio
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: app-port
    - protocol: TCP
      port: 3100
      targetPort: 3100
      name: admin-port
    - protocol: TCP
      port: 3170
      targetPort: 3170
      name: backend-port
    - protocol: TCP
      port: 3080
      targetPort: 80
      name: web-port
