{{- if not .Values.hoppscotch.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app.kubernetes.io/name: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
type: Opaque
data:
  jwt_secret: {{ .Values.hoppscotch.auth.JWT_SECRET | b64enc | quote }}
  session_secret: {{ .Values.hoppscotch.auth.SESSION_SECRET | b64enc | quote }}
  mailer_smtp_password: {{ .Values.hoppscotch.auth.MAILER_SMTP_PASSWORD | b64enc | quote }}
  data_encryption_key: {{ .Values.hoppscotch.auth.DATA_ENCRYPTION_KEY | b64enc | quote }}
{{- end }}
