apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-aio
spec:
  selector:
    app: {{ .Release.Name }}-aio
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http-web-port
    - protocol: TCP
      port: 3100
      targetPort: 3100
      name: http-admin-port
    - protocol: TCP
      port: 3170
      targetPort: 3170
      name: backend-port
