{{- if .Values.matcher.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matcher
  labels:
    {{- include "AGH2.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: matcher
  template:
    metadata:
      labels:
        app: matcher
    spec:
      {{- include "matcher.imagePullSecrets" . | nindent 6 }}
      initContainers:
        - name: exploitmgr-init-postgresql
          image: {{ include "db.image" . }}
          env:
            - name: PG_CONN_STR
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.exploitmgr.secret.db.secretName }}
                  key: DB_CONN_STR
          command:
            [
              "sh",
              "-c",
              "until pg_isready -d $PG_CONN_STR; do echo waiting for postgresql; sleep 1; done",
            ]
      containers:
        - name: matcher
          image: {{ include "matcher.image" . }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if .Values.core.enabled }}
            - name: CORE_URL
              value: "core.$(NAMESPACE).svc.cluster.local:50005"
            {{- end }}
            {{- if .Values.matcher.extraEnv }}
            {{- include "common.tplvalues.render" (dict "value" .Values.matcher.extraEnv "context" $) | nindent 12 }}
            {{- end }}
          command:
            - ./matcher
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - name: grpc
              containerPort: 50005
          imagePullPolicy: {{ .Values.matcher.image.pullPolicy }}
      restartPolicy: "Always"
{{- end }}
