{{- if and .Values.clusterFeatureEnabler.enabled .Values.clusterFeatureEnabler.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clusterFeatureEnabler.serviceAccountName" . }}
  labels:
    {{- include "AGH3.labels" . | nindent 4 }}
{{- end }}
