{{- if and .Values.clusterFeatureEnabler.enabled .Values.clusterFeatureEnabler.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "clusterFeatureEnabler.serviceAccountName" . }}-clusterrolebinding
  labels:
    {{- include "AGH3.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ include "clusterFeatureEnabler.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
