{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    {{- include "AGH2.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      {{- include "redis.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: redis
          image: {{ include "redis.image" . }}
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - name: redis
              containerPort: 6379
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
{{- end }}
