{{- if and .Values.actionLoop.enabled .Values.actionLoop.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "actionLoop.serviceAccountName" . }}
  labels:
    {{- include "AGH3.labels" . | nindent 4 }}
{{- end }}
