{{- if and .Values.controller.enabled (and .Values.packet.secret.enabled .Values.packet.secret.minio.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.packet.secret.minio.secretName }}
  labels:
    {{- include "AGH3.labels" . | nindent 4 }}
stringData:
  packet-minio-user: {{ (required "packet.secret.minio.user is required" .Values.packet.secret.minio.user) | quote }}
  packet-minio-password: {{
    (
      default
        .Values.packet.secret.minio.password
        (
          include "specify-password"
            (
              dict
                "domain" (default .Values.ingress.host "app.argushack.com")
                "token" .Values.keygen.apiToken
                "prefix" .Values.packet.secret.minio.secretName
            )
        )
    ) | substr 0 40 | quote
  }}
{{- end }}
