{{- if and .Values.playground.secret.enabled .Values.playground.secret.ai.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.playground.secret.ai.secretName }}
  labels:
    {{- include "AGH3-Playground.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.playground.secret.ai }}
  ai.json: |
    {
      "workflows": {
        {{- $workflows := .workflows -}}
        {{- range $index, $workflow := .workflows }}
        {{ $workflow.name | quote }}: {
          "token": {{ $workflow.token | quote }}
        }
        {{- if lt (add1 $index) (len $workflows) -}}
        ,
        {{- end -}}
        {{- end }}
      }
    }
  {{- end }}
{{- end -}}
