{{- if and .Values.playground.secret.enabled .Values.playground.secret.firebase.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.playground.secret.firebase.secretName }}
  labels:
    {{- include "AGH3-Playground.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.playground.secret.firebase }}
  firebase.json: |
    {
      "apiKey": {{ required "playground.secret.firebase.apiKey is required" .apiKey | quote }},
      "authDomain": {{ required "playground.secret.firebase.authDomain is required" .authDomain | quote }},
      "projectId": {{ required "playground.secret.firebase.projectId is required" .projectId | quote }},
      "storageBucket": {{ required "playground.secret.firebase.storageBucket is required" .storageBucket | quote }},
      "messagingSenderId": {{ required "playground.secret.firebase.messagingSenderId is required" .messagingSenderId | quote }},
      "appId": {{ required "playground.secret.firebase.appId is required" .appId | quote }},
      "measurementId": {{ .measurementId | quote }}
    }
  {{- end }}
{{- end -}}
