{{- if and .Values.playground.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: playground
  labels:
    {{- include "AGH3-Playground.labels" . | nindent 4 }}
spec:
  selector:
    app: playground
  ports:
    - port: 80
      targetPort: web
{{- end }}
