{{- if .Values.transformer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: transformer
  labels:
    {{- include "AGH2.labels" . | nindent 4 }}
spec:
  selector:
    app: transformer
  ports:
    - port: 50005
      targetPort: grpc
{{- end }}
