{{- if and .Values.core.enabled .Values.core.secret.enabled .Values.core.secret.db.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.core.secret.db.secretName }}
  labels:
    {{- include "AGH2.labels" . | nindent 4 }}
stringData:
  DB_CONN_STR: {{ include "connection-string"
    (
      dict
        "db" (
          merge
            .Values.core.secret.db
            .Values.db.connection
            (
              dict
                "password" (
                  include "specify-password"
                    (
                      dict
                        "domain" (default .Values.ingress.host "app.argushack.com")
                        "token" .Values.keygen.apiToken
                        "prefix" .Values.core.secret.db.secretName
                    )
                )
            )
        )
        "context" $
    ) | quote }}
{{- end }}
