{{- if and .Values.core.enabled (and .Values.core.secret.enabled .Values.core.secret.minio.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.core.secret.minio.secretName }}
  labels:
    {{- include "AGH2.labels" . | nindent 4 }}
data:
  {{- with .Values.core.secret.minio }}
  core-minio-user: {{ printf .user | b64enc | quote }}
  core-minio-password: {{ printf .password | b64enc | quote }}
  {{- end }}
{{- end }}
