{{- if and .Values.core.enabled (and .Values.core.secret.enabled .Values.core.secret.minio.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.core.secret.minio.secretName }}
  labels:
    {{- include "AGH2.labels" . | nindent 4 }}
stringData:
  core-minio-user: {{ (required "core.secret.minio.user is required" .Values.core.secret.minio.user) | quote }}
  core-minio-password: {{
    (
      default
        .Values.core.secret.minio.password
        (
          include "specify-password"
            (
              dict
                "domain" (default .Values.ingress.host "app.argushack.com")
                "token" .Values.captain.secret.keygen.apiToken
                "prefix" .Values.core.secret.minio.secretName
            )
        )
    ) | quote
  }}
{{- end }}
