{{- if and .Values.core.enabled (and .Values.core.secret.enabled .Values.core.secret.minio.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.core.secret.minio.secretName }}
  labels:
    {{- include "AGH2.labels" . | nindent 4 }}
stringData:
  {{- with .Values.core.secret.minio }}
  capt-minio-user: {{ (required "core.secret.minio.user is required" .user) | quote }}
  capt-minio-password: {{ (required "core.secret.minio.password is required" .password) | quote }}
  {{- end }}
{{- end }}
