{{- if and .Values.parser.secret.enabled .Values.parser.secret.sa.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.parser.secret.sa.secretName}}
  labels:
    {{- include "AGH3.labels" . | nindent 4 }}
stringData:
  sa.json: {{ .Values.parser.secret.sa.json | quote}}
{{- end }}
