{{- if .Values.minio.internal }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: agh-minio-cm
  labels:
    {{- include "AGH3.labels" . | nindent 4 }}
data:
  MINIO_NOTIFY_WEBHOOK_ENABLE_PRIMARY: "on"
  MINIO_NOTIFY_WEBHOOK_ENDPOINT_PRIMARY: "http://captain.{{ .Release.Namespace }}.svc.cluster.local:8080/internal/webhook/minio"
{{- end }}
