{{- if and .Values.minio.internal .Values.minio.provisioning.enabled .Values.minio.provisioning.generateUser }}
apiVersion: v1
kind: Secret
metadata:
  name: agh-minio-users-secret
type: Opaque
stringData:
  {{ .Values.captain.secret.minio.user }}: |
    username={{ .Values.captain.secret.minio.user }}
    password={{
      (
        default
          .Values.captain.secret.minio.password
          (
            include "specify-password"
              (
                dict
                  "domain" (default .Values.ingress.host "app.argushack.com")
                  "token" .Values.captain.secret.keygen.apiToken
                  "prefix" .Values.captain.secret.minio.secretName
              )
          )
      ) | substr 0 40
    }}
    disabled=false
    policies=readwrite
    setPolicies=false
  {{ .Values.core.secret.minio.user }}: |
    username={{ .Values.core.secret.minio.user }}
    password={{
      (
        default
          .Values.core.secret.minio.password
          (
            include "specify-password"
              (
                dict
                  "domain" (default .Values.ingress.host "app.argushack.com")
                  "token" .Values.captain.secret.keygen.apiToken
                  "prefix" .Values.core.secret.minio.secretName
              )
          )
      ) | substr 0 40
    }}
    disabled=false
    policies=readonly
    setPolicies=false
{{- end }}
