{{- if and .Values.minio.internal .Values.minio.provisioning.enabled .Values.minio.provisioning.generateUser }}
apiVersion: v1
kind: Secret
metadata:
  name: agh-minio-users-secret
type: Opaque
stringData:
  {{- with .Values.captain.secret.minio }}
  {{ .user }}: |
    username={{ .user }}
    password={{ .password }}
    disabled=false
    policies=readwrite
    setPolicies=false
  {{- end }}
  {{- with .Values.core.secret.minio }}
  {{ .user }}: |
    username={{ .user }}
    password={{ .password }}
    disabled=false
    policies=readonly
    setPolicies=false
  {{- end }}
{{- end }}
