{{- if and .Values.ingress.tls.enabled (not (empty .Values.ingress.host)) }}
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: default
spec:
  defaultCertificate:
    secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}
