{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.secret.secretName }}
  labels:
    {{- include "AGH3.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{
      default 
        .Values.redis.secret.password
        (
          include "specify-password"
            (
              dict
                "domain" (default .Values.ingress.host "app.argushack.com")
                "token" .Values.keygen.apiToken
                "prefix" .Values.redis.secret.secretName
            )
        )
    | quote
  }}
{{- end }}
