{{- if .Values.blender.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blender
  labels:
    {{- include "AGH2-helm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: blender
  template:
    metadata:
      labels:
        app: blender
    spec:
      initContainers:
        - name: blender-init-redis
          image: redis
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ENV_REDIS_CONN
              value: "redis://redis.$(NAMESPACE).svc.cluster.local:6379/0"
          command:
            [
              "sh",
              "-c",
              "until redis-cli --no-auth-warning -u $ENV_REDIS_CONN ping; do echo waiting for redis; sleep 1; done",
            ]
      containers:
        - name: blender
          image: "{{ .Values.blender.image.repository }}:{{ .Values.blender.image.tag }}"
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ENV_REDIS_CONN
              value: "redis://redis.$(NAMESPACE).svc.cluster.local:6379/0"
            - name: CORE_URL
              value: "core.$(NAMESPACE).svc.cluster.local:50005"
          command: ["./blender"]
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: grpc
              containerPort: 50005
          imagePullPolicy: {{ .Values.blender.image.pullPolicy }}
      imagePullSecrets:
        - name: gitlab-registry
      restartPolicy: "Always"
{{- end }}