apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    {{- include "AGH2-helm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6-alpine
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: redis
              containerPort: 6379
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
