{{- if and .Values.report.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: report
  labels:
    {{- include "AGH3.labels" . | nindent 4 }}
spec:
  selector:
    app: report
  ports:
    - port: 80
      targetPort: web
{{- end }}
