{{- if .Values.ingress.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.secretName }}
  namespace: default
data:
  tls.crt: {{ .Values.ingress.tls.cert }}
  tls.key: {{ required "invalid Values ingress.tls.key!" .Values.ingress.tls.key }}
{{- end }}
