{{- if .Values.minio.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.minio.secret.secretName }}
  labels:
    {{- include "AGH2.labels" . | nindent 4 }}
stringData:
{{- if eq .Values.minio.connection.type "internal" }}
  url: {{ printf "minio.%s.svc.cluster.local" $.Release.Namespace | quote }}
{{- else }}
  {{- with .Values.minio.connection }}
  url: {{ printf "%v:%v" .host .port | quote }}
  {{- end }}
{{- end }}
{{- end }}
