{{- if .Values.minio.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.minio.secret.secretName }}
  labels:
    {{- include "AGH2.labels" . | nindent 4 }}
data:
  {{- with .Values.minio }}
  url: {{- printf "%v:%v" .host .port | b64enc | quote }}
  {{- end }}
{{- end }}
