name: ⚙️ [AGH2] Release Charts

on:
  push:
    branches:
      - main
    paths:
      - charts/agh2/**

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Add Helm dependency repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Dump .version.json
        id: versions
        run: |
          VERSION=$(cat .version.json)
          echo "::set-output name=version::${VERSION}"

      - name: Invoke workflow Update ArgusHack in Leukocyte-Lab/ArgusHack2
        run: |
         echo '{"version": ${{ toJson(steps.versions.outputs.version) }}}' | gh workflow -R Leukocyte-Lab/ArgusHack2 run agh2-update.yml -r develop --json
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
