name: ⚙️ [AGH2] Release Charts

on:
  push:
    branches:
      - main
    paths:
      - charts/agh2/**
      - .github/workflows/agh2-release.yaml

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: src
          fetch-depth: 0

      - name: 🔔 Checkout
        uses: actions/checkout@v4
        with:
          path: dest
          ref: "gh-pages"
          fetch-depth: 0

      - name: 🪝 Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.13.3

      - name: 📦 Packing Helm Charts
        shell: bash
        run: |
          helm dep up src/charts/agh2
          helm package src/charts/agh2 -u -d dest

      - name: 🎁 Release Chart
        shell: bash
        working-directory: dest
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          helm repo index . --url https://charts.lkc-lab.com/ --merge index.yaml 
          git add $(git ls-files -o --exclude-standard)
          git add index.yaml
          git commit -m "Release from ref: $GITHUB_SHA"
          git push
