name: AutoMerge

on:
  pull_request:
    types:
      - opened
    branches:
      - main
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.pull_request.title, 'auto-build:') }}
        with:
          labels: automerge
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/checkout@v4
        with:
          repository: Leukocyte-Lab/AGH2-Manifest
          token: ${{ secrets.GH_TOKEN }}
      - name: dump .version.json
        id: versions
        run: |
          VERSION=$(cat .version.json)
          echo "::set-output name=version::${VERSION}"
      - name: Invoke workflow Update ArgusHack in Leukocyte-Lab/ArgusHack2
        run: |
         echo '{"version": ${{ toJson(steps.versions.outputs.version) }}}' | gh workflow -R Leukocyte-Lab/ArgusHack2 run agh2-update.yml -r develop --json
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
