{{- if .Values.captain.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: captain
  labels:
    {{- include "AGH2.labels" . | nindent 4 }}
spec:
  selector:
    app: captain
  ports:
    - port: 9527
      targetPort: http
{{- end }}
