{{- if .Values.captain.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: captain
  labels:
    {{- include "AGH2.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: captain
  template:
    metadata:
      labels:
        app: captain
    spec:
      {{- include "captain.imagePullSecrets" . | nindent 6 }}
      initContainers:
        {{- if and .Values.redis.enabled .Values.attack.service.redis.enabled }}
        - name: captain-init-redis
          image: {{ include "redis.image" . }}
          command:
            [
              "sh",
              "-c",
              "until redis-cli --no-auth-warning -h $REDIS_SERVICE_HOST -p $REDIS_SERVICE_PORT ping; do echo waiting for redis; sleep 1; done",
            ]
        {{- end }}
        - name: captain-init-postgresql
          image: {{ include "db.image" . }}
          env:
            - name: PG_CONN_STR
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.captain.secret.db.secretName }}
                  key: DB_CONN_STR
          command:
            [
              "sh",
              "-c",
              "until pg_isready -d $PG_CONN_STR; do echo waiting for postgresql; sleep 1; done",
            ]
      containers:
        - name: captain
          image: {{ include "captain.image" . }}
          command:
            - ./captain
          envFrom:
            - prefix: SYSIMG_
              configMapRef:
                name: {{ .Values.shared.configMapName }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if and .Values.redis.enabled .Values.captain.service.redis.enabled }}
            - name: ENV_REDIS_CONN
              value: "redis://redis.$(NAMESPACE).svc.cluster.local:6379/0"
            {{- end }}
            {{- if .Values.core.enabled }}
            - name: CORE_URL
              value: "core.$(NAMESPACE).svc.cluster.local:50005"
            {{- end }}
            {{- if .Values.exploitmgr.enabled }}
            - name: EXPMGR_URL
              value: "exploitmgr.$(NAMESPACE).svc.cluster.local:50005"
            {{- end }}
            {{- if .Values.template.enabled }}
            - name: TEMPLATE_URL
              value: "template.$(NAMESPACE).svc.cluster.local:50005"
            {{- end }}
            - name: DB_Conn
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.captain.secret.db.secretName }}
                  key: DB_CONN_STR
            - name: Addr
              value: ":9527"
            - name: SECRET_JWT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.captain.secret.jwt.secretName }}
                  key: jwt-secret
            - name: "KEYGEN_ACCOUNT_ID"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keygen.secretName }}
                  key: account-id
            - name: "KEYGEN_API_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keygen.secretName }}
                  key: api-token
            - name: MINIO_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.secret.secretName }}
                  key: url
            - name: MINIO_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.captain.secret.minio.secretName }}
                  key: capt-minio-user
            - name: MINIO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.captain.secret.minio.secretName }}
                  key: capt-minio-password
            {{- if .Values.attack.extraEnv }}
            {{- include "common.tplvalues.render" (dict "value" .Values.captain.extraEnv "context" $) | nindent 12 }}
            {{- end }}
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 9527
          imagePullPolicy: {{ .Values.captain.image.pullPolicy }}
      restartPolicy: "Always"
{{- end }}
